### ISSUE TITLE
Run problem

### ISSUE THREAD

**Issue by strive160** [liaohaofu/adn#10]
I ran your code, but this problem occurred, because It was ok when I ran it before. I recently installed a new environment, I wonder whether the current pytorch version does not fit your code or what
Here's the problem
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 256, 4, 4]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by liaohaofu** [comment]
Hi, it is likely caused by the incorrect version of Pytorch. I didn't try
my code with newer versions. So there might be unknown issues. Can you
switch back to older (say using conda environment) version as noted in my
installation requirement and see if that fixes it?
