### ISSUE TITLE
Some questions on CNN-MAR

### ISSUE THREAD

**Issue by strive160** [liaohaofu/adn#13]
I'm sorry that I shouldn't have bothered you, but the original author of this article is not replying now. I would like to ask how you reproduced his production data set, or how you generated the data set with his method when using the spine data set, and how you used code to simulate images with metal artifacts.Can you share your code?You can check out his github question, but he didn't respond.I'm still a green hand, I hope you can help me
Thank you very much

**Comment by liaohaofu** [comment]
Sorry, but due to my time constraint I can only respond to problems with regard to my own code/repo. Please try other ways to contact the CNNMAR authors for solutions. Thanks!
