### ISSUE TITLE
One of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by audreyeternal** [liaohaofu/adn#21]
I have been stuck in an error showing up when trying to train the model. The dataset that I used is `spineweb`. The error is as follows:
![错误1](https://user-images.githubusercontent.com/71795670/112804277-84969800-9074-11eb-8d9e-5c53fd9f390e.jpg)
The traceback shows that there exists an inplace operation that modify the node in the computational graph. 
The configuration of my environment: operating system: debian 10, pytorch version: 1.7, python version: 3.7.10.

**Comment by liaohaofu** [comment]
Hey Yu, can you try Pytorch 1.0.0 instead? This is an somewhat old repo and may not work with higher versions of Pytorch (I didn't get to test it lately). Thanks!

**Comment by audreyeternal** [comment]
Thank you for your reply！I will try it later.
