### ISSUE TITLE
about Test Results

### ISSUE THREAD

**Issue by ke-dev** [liaohaofu/adn#23]
Hello, there is a question that bothers me, can the test result be a 3D picture, thank you for your answer.

**Comment by liaohaofu** [comment]
No, by default the network supports only 2d images.

**Comment by ke-dev** [comment]
there are dozens of test pictures in one data, but why are there only a few test results? What is the reason? Thank you for your answer

**Comment by ke-dev** [comment]
It's about the deep_lesion data set

**Comment by liaohaofu** [comment]
Which results are you referring to? In the paper, the number is averaged
number for the entire dataset. In the demo, we only show several examples.
In the test, we evaluate all samples.
