### ISSUE TITLE
Image without artifact is denoted as low quality image？

### ISSUE THREAD

**Issue by DamperHa** [liaohaofu/adn#5]
https://github.com/liaohaofu/adn/blob/61d2caa28936d53bbdb1bfe4db867fa6ef607634/adn/networks/adn.py#L96 Hello, I want to confirm, is this a typo or is this really defined in the code?

**Comment by liaohaofu** [comment]
Thanks for pointing out. This is a typo. I will correct it later.

-Haofu

**Comment by liaohaofu** [comment]
The typo has been corrected.
