### ISSUE TITLE
可以提供一下与训练模型和数据的网盘下载链接吗？

### ISSUE THREAD

**Issue by brisyramshere** [liaohaofu/adn#6]
google driver被强了上不上去。

**Comment by brisyramshere** [comment]
或者能上传到github上也行，谢谢啦！

**Comment by liaohaofu** [comment]
Hi, I have uploaded the pretrained models to bitbucket, you can access them from [here](https://bitbucket.org/liaohaofu/adn_modesl). For the datasets, we do not own them and thus cannot redistribute without the authors' permission. Please contact the authors of DeepLesion and Spineweb directly for access.

**Comment by brisyramshere** [comment]
thank you very much!
