### ISSUE TITLE
THE WGANGP is not right？

### ISSUE THREAD

**Issue by brisyramshere** [liaohaofu/adn#7]
have no gradient penalty term？

**Comment by liaohaofu** [comment]
Hi, the GANLoss class is adopted from the [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) repo which provides WGANGP. In our work, we use LSGAN by default and WGANGP is not fully supported. You may refer [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/b21e552cf26bc6dbafd8161f77662367804a13c4/models/networks.py#L278) for the GP calculation.

**Comment by brisyramshere** [comment]
thank you very much
